# Generated by Django 5.1.3 on 2024-11-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
